name: Create Release with Changelog

on:
  push:
    tags:
      - 'v*.*.*'  

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run compare_changelog.sh
      run: ./script/compare_changelog.sh


    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:          
        body: ./script/changelog.txt 
