name: Create Release with Changelog

on:
  push:
    tags:
      - 'v*.*.*'  

jobs:
  release:
    runs-on: ubuntu-latest    

    steps:
    - name: Checkout code
      uses: actions/checkout@v4     

    - name: Run automatic changelog
      uses: ./.github/actions/auto-changelog
      with:
        file: 'CHANGELOG.md'
    

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ./changelog.txt    
