name: Create Release with Changelog

on:
  push:
    tags:
      - 'v*.*.*'  

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4     

    - name: Run compare_changelog.sh  
      run: |
        # Define o arquivo do changelog
        CHANGELOG_FILE="CHANGELOG.md"

        echo # Changelog > auto_changelog.txt

        # Lê o conteúdo do changelog e extrai o último conteúdo
        awk '
        BEGIN { inside_section = 0; }
        /^## v[0-9]+/ {
        if (inside_section == 1) {
            exit;
        }
        inside_section = 1;
        next;
        }
        inside_section == 1 {
        print;
        }' "$CHANGELOG_FILE" >> auto_changelog.txt 

        ls


    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ./auto_changelog.txt    
