name: Create Release with Changelog

on:
  push:
    tags:
      - 'v*.*.*'  

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Garantir que todo o histórico seja buscado

    - name: Run compare_changelog.sh
      run: |
        ./script/changelog.sh
        ls


    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ./auto_changelog.txt    
